// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import {Test, console} from "forge-std/Test.sol";

/// @title Visual Fuzzing Demo with Detailed Logs
/// @notice This demonstrates Foundry's fuzzer generating random inputs with visible logging
contract FuzzVisualDemo is Test {
    
    uint256 public runCount;
    
    /// @notice Regular test - always the same inputs
    function test_RegularTest_FixedInputs() public {
        console.log("\n=");
        console.log("  REGULAR TEST - Fixed Inputs");
        console.log("=");
        
        uint256 x = 42;  // Always 42
        uint256 y = 100; // Always 100
        
        console.log("x (fixed):", x);
        console.log("y (fixed):", y);
        console.log("Result:", x + y);
        console.log("This test runs ONCE with the same values every time");
        
        assertEq(x + y, 142);
    }
    
    /// @notice Fuzz test - Foundry generates RANDOM inputs!
    /// @param x Random uint256 generated by Foundry
    /// @param y Random uint256 generated by Foundry
    function testFuzz_RandomInputs_SeeTheMagic(uint256 x, uint256 y) public {
        runCount++;
        
        console.log("\n========================================");
        console.log("  FUZZ TEST - Random Inputs");
        console.log("========================================");
        console.log("Run number:", runCount);
        console.log("x (RANDOM):", x);
        console.log("y (RANDOM):", y);
        console.log("Result:", x + y);
        console.log("Notice: x and y are DIFFERENT every run!");
        console.log("Foundry generated these randomly!");
        
        // Property that should hold for ALL inputs
        assertTrue(x + y >= x, "Addition property: result >= x");
        assertTrue(x + y >= y, "Addition property: result >= y");
    }
    
    /// @notice Fuzz test with bounds - random values within a range
    /// @param value Random value (will be bounded to 1-100)
    function testFuzz_BoundedRandom(uint256 value) public {
        runCount++;
        
        // Bound the random input to a specific range
        uint256 boundedValue = bound(value, 1, 100);
        
        console.log("\n========================================");
        console.log("  FUZZ TEST - Bounded Random");
        console.log("========================================");
        console.log("Run number:", runCount);
        console.log("Original random value:", value);
        console.log("Bounded value (1-100):", boundedValue);
        console.log("Foundry generated:", value);
        console.log("We bounded it to:", boundedValue);
        
        assertGe(boundedValue, 1);
        assertLe(boundedValue, 100);
    }
    
    /// @notice Fuzz test showing multiple random parameters
    /// @param a Random uint256
    /// @param b Random uint8
    /// @param c Random bool
    /// @param d Random address (as uint160)
    function testFuzz_MultipleRandomParams(
        uint256 a,
        uint8 b,
        bool c,
        uint160 d
    ) public {
        runCount++;
        
        address randomAddress = address(d);
        
        console.log("\n========================================");
        console.log("  FUZZ TEST - Multiple Random Params");
        console.log("========================================");
        console.log("Run number:", runCount);
        console.log("a (uint256, RANDOM):", a);
        console.log("b (uint8, RANDOM):", b);
        console.log("c (bool, RANDOM):", c);
        console.log("d (address, RANDOM):", randomAddress);
        console.log("All values are randomly generated by Foundry!");
    }
    
    /// @notice Fuzz test that will find edge cases
    /// @param x Random value
    function testFuzz_EdgeCaseFinder(uint256 x) public {
        runCount++;
        
        console.log("\n========================================");
        console.log("  FUZZ TEST - Edge Case Finder");
        console.log("========================================");
        console.log("Run number:", runCount);
        console.log("Random x:", x);
        
        // Bound to find edge cases near boundaries
        uint256 bounded = bound(x, 0, 100);
        console.log("Bounded x (0-100):", bounded);
        
        if (bounded == 0) {
            console.log(">>> Found edge case: x = 0 (minimum)");
        }
        if (bounded == 100) {
            console.log(">>> Found edge case: x = 100 (maximum)");
        }
        if (bounded == 1) {
            console.log(">>> Found edge case: x = 1 (near minimum)");
        }
        if (bounded == 99) {
            console.log(">>> Found edge case: x = 99 (near maximum)");
        }
        
        assertLe(bounded, 100);
    }
    
    /// @notice Fuzz test showing how Foundry finds bugs
    /// @param x Random value
    function testFuzz_BugFinder(uint256 x) public {
        runCount++;
        
        console.log("\n========================================");
        console.log("  FUZZ TEST - Bug Finder");
        console.log("========================================");
        console.log("Run number:", runCount);
        console.log("Random x:", x);
        
        // This will fail when x > 1000
        // Foundry will find the exact value that breaks it!
        if (x > 1000) {
            console.log(">>> [BUG FOUND] x > 1000:", x);
            console.log(">>> Foundry discovered this edge case!");
        }
        
        assertLe(x, 1000, "This will fail when Foundry generates x > 1000");
    }
    
    /// @notice Fuzz test with array inputs
    /// @param values Random array of 5 uint256 values
    function testFuzz_RandomArray(uint256[5] memory values) public {
        runCount++;
        
        console.log("\n========================================");
        console.log("  FUZZ TEST - Random Array");
        console.log("========================================");
        console.log("Run number:", runCount);
        console.log("Array[0] (RANDOM):", values[0]);
        console.log("Array[1] (RANDOM):", values[1]);
        console.log("Array[2] (RANDOM):", values[2]);
        console.log("Array[3] (RANDOM):", values[3]);
        console.log("Array[4] (RANDOM):", values[4]);
        console.log("Foundry generated 5 random values!");
        
        // Sum should be >= each element
        uint256 sum = values[0] + values[1] + values[2] + values[3] + values[4];
        console.log("Sum of all values:", sum);
        
        assertTrue(sum >= values[0]);
    }
    
    /// @notice Fuzz test showing statistical distribution
    /// @param value Random value
    function testFuzz_StatisticalDistribution(uint256 value) public {
        runCount++;
        
        // Bound to 0-1000 for easier viewing
        uint256 bounded = bound(value, 0, 1000);
        
        console.log("\n========================================");
        console.log("  FUZZ TEST - Statistical Distribution");
        console.log("========================================");
        console.log("Run number:", runCount);
        console.log("Random value (0-1000):", bounded);
        
        // Categorize the random value
        if (bounded < 100) {
            console.log(">>> Category: Low (0-99)");
        } else if (bounded < 500) {
            console.log(">>> Category: Medium (100-499)");
        } else if (bounded < 900) {
            console.log(">>> Category: High (500-899)");
        } else {
            console.log(">>> Category: Very High (900-1000)");
        }
        
        assertLe(bounded, 1000);
    }
}

