// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import {Test, console} from "forge-std/Test.sol";

/// @title Fuzzing Demo - Shows the Difference Between Regular and Fuzz Tests
/// @notice This demonstrates how Foundry's fuzzer generates random inputs
contract FuzzDemo is Test {
    
    /// @notice Regular test - runs ONCE with fixed inputs
    function test_RegularTest() public {
        uint256 x = 5;  // Fixed value
        uint256 y = 10; // Fixed value
        
        console.log("=== REGULAR TEST ===");
        console.log("x:", x);
        console.log("y:", y);
        console.log("Result:", x + y);
        
        assertEq(x + y, 15); // Always the same
    }
    
    /// @notice Fuzz test - Foundry generates RANDOM inputs automatically!
    /// @param x Random value generated by Foundry
    /// @param y Random value generated by Foundry
    function testFuzz_RandomInputs(uint256 x, uint256 y) public {
        // Foundry automatically generates random x and y!
        // Run with: forge test --match-test testFuzz_RandomInputs -vvv --fuzz-runs 10
        
        console.log("=== FUZZ TEST (Random Inputs) ===");
        console.log("x:", x);
        console.log("y:", y);
        console.log("Result:", x + y);
        
        // This property should hold for ALL inputs
        assertTrue(x + y >= x, "Addition property");
        assertTrue(x + y >= y, "Addition property");
    }
    
    /// @notice Fuzz test with bounds - Foundry generates random values within range
    /// @param value Random value between 1 and 100 (generated by Foundry)
    function testFuzz_BoundedInputs(uint256 value) public {
        // Bound the random input to a reasonable range
        value = bound(value, 1, 100);
        
        console.log("=== FUZZ TEST (Bounded Inputs) ===");
        console.log("Random value (1-100):", value);
        
        // Test that value is always in range
        assertGe(value, 1);
        assertLe(value, 100);
    }
    
    /// @notice Fuzz test showing multiple random parameters
    /// @param a Random uint256
    /// @param b Random uint8  
    /// @param c Random bool
    function testFuzz_MultipleParams(uint256 a, uint8 b, bool c) public {
        console.log("=== FUZZ TEST (Multiple Random Params) ===");
        console.log("a (uint256):", a);
        console.log("b (uint8):", b);
        console.log("c (bool):", c);
        
        // Foundry generates random combinations:
        // Run 1: a=12345, b=42, c=true
        // Run 2: a=999999, b=0, c=false
        // Run 3: a=0, b=255, c=true
        // ... etc for 256 runs!
    }
    
    /// @notice This will FAIL for some random inputs - demonstrates fuzzing finding bugs!
    /// @param x Random value
    function testFuzz_WillFail(uint256 x) public {
        // This test will FAIL when Foundry generates x > 100
        // Foundry will show you the exact value that broke it!
        
        console.log("=== FUZZ TEST (Will Find Failure) ===");
        console.log("Random x:", x);
        
        // This assertion will fail for some random inputs
        assertLe(x, 100, "This will fail when x > 100");
    }
}

